### ISSUE TITLE
Would you please add a license file for this repo?

### ISSUE THREAD

**Issue by winguse** [tamediadigital/grpc-gatling#1]
Thanks for sharing the code, it looks really good. But I cannot find any license information. Would you please add a license file for this repo?

**Comment by yannick** [comment]
@winguse  what license would you prefer?
@igormiletic  can you add one? we usually used boost for D project but it doesnt matter. MIT or apache are fine too.

**Comment by winguse** [comment]
Either MIT or apache is welcome. I just have some legal concerns when referencing your code. And thanks again for your contribution :)

**Comment by ManuelWeiss** [comment]
Hi @yannick @igormiletic could you please add a license - have the same issue, don't want to use your code without a license...

**Comment by igormiletic** [comment]
@ManuelWeiss @winguse MIT licence added.

**Comment by ManuelWeiss** [comment]
Awesome, thanks a lot.
